/**
 * Mentor Types
 *
 * Type definitions for the Alert Service and Mentor Router.
 */

/** Alert severity level based on Z-score and percent change thresholds */
export type AlertLevel = "vermelho" | "amarelo" | "verde";

/** Types of alerts that can be triggered */
export type AlertType =
  | "sem_registro"
  | "registro_atrasado"
  | "meta_nao_atingida"
  | "queda_abrupta"
  | "zscore";

/** Metrics that can trigger alerts */
export type AlertMetric = "faturamento" | "leads" | "procedimentos";

/**
 * Alert object representing a warning or issue for a mentorado
 */
export interface Alert {
  tipo: AlertType;
  metrica?: AlertMetric;
  level: AlertLevel;
  zScore?: number;
  percentChange?: number;
  message: string;
  usedFallback?: boolean;
}

/**
 * Result of alert calculation with metadata
 */
export interface AlertCalculationResult {
  alerts: Alert[];
  usedFallback: boolean;
  fallbackMonth?: { ano: number; mes: number };
}

/**
 * Topic suggestions generated by AI or fallback rules
 */
export interface TopicSuggestions {
  suggestions: string[];
  source: "ai" | "fallback";
}

/**
 * Input for call preparation
 */
export interface CallPreparationInput {
  mentoradoId: number;
}

/**
 * Metrics data structure for comparison
 */
export interface MetricsData {
  faturamento: number;
  leads: number;
  procedimentos: number;
  lucro?: number;
  postsFeed?: number;
  stories?: number;
}

/**
 * Call preparation payload aggregating all data for a call
 */
export interface CallPreparationPayload {
  mentorado: {
    id: number;
    nomeCompleto: string;
    fotoUrl: string | null;
    email: string | null;
    turma: string;
    metaFaturamento: number;
  };
  currentMetrics: MetricsData | null;
  alerts: Alert[];
  evolution: Array<{
    ano: number;
    mes: number;
    faturamento: number;
    leads: number;
    procedimentos: number;
  }>;
  comparison: {
    userMetrics: MetricsData | null;
    turmaAverage: MetricsData | null;
    percentiles: Record<string, number> | null;
  } | null;
  lastCallNotes: {
    id: number;
    dataCall: Date;
    principaisInsights: string;
    acoesAcordadas: string;
    proximosPassos: string;
    duracaoMinutos: number | null;
  } | null;
  suggestions: TopicSuggestions;
}

/**
 * Upcoming call from calendar with alert indicators
 */
export interface UpcomingCall {
  eventId: string;
  title: string;
  start: Date;
  end: Date;
  mentoradoId: number | null;
  mentoradoNome: string | null;
  alerts: Alert[];
}
